version: "3"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - caddy_network
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy:

networks:
  caddy_network:
    external: true